import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link, Navigate, Outlet, useLocation, useNavigate, useOutletContext, useParams } from 'react-router-dom';
import { Archive, ArrowDown, ArrowLeft, ArrowRight, BookOpen, CalendarDays, ChevronRight, LogOut, Plus, QrCode, Search } from 'lucide-react';
import { useAuth } from './auth';
import { allPages, api, ApiError, date, message, supabase } from './lib';
import { Brand, ErrorNotice, Loading, Modal } from './ui';
import type { ClassItem, Course, Profile } from './types';

export function AdminLayout() {
  const { ready, session } = useAuth(); const [profile, setProfile] = useState<Profile | null>(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  const [signingOut, setSigningOut] = useState(false); const location = useLocation();
  useEffect(() => {
    if (!session) return; let active = true; setError('');
    api<Profile>('/me').then(p => { if (active) setProfile(p); }).catch(e => { if (active) setError(message(e)); });
    return () => { active = false; };
  }, [session?.user.id, retry]);
  async function logout() { setSigningOut(true); const result = await supabase?.auth.signOut(); if (result?.error) { setError('No pudimos cerrar la sesión. Intentá nuevamente.'); setSigningOut(false); } }
  if (!ready) return <Loading />;
  if (!session) return <Navigate to="/login" replace />;
  if (!profile || profile.role !== 'ADMIN') return <main className="center-page"><Brand />{error ? <ErrorNotice text={error} retry={() => setRetry(n => n + 1)} /> : !profile ? <Loading text="Abriendo tus cursos…" /> : <div className="access-card"><BookOpen size={32} /><h1>Todo empieza con un QR.</h1><p>Para registrar tu asistencia, escaneá el código de tu profesor.</p><p className="small muted">Si sos profesor, pedí que habiliten esta cuenta.</p></div>}<button className="text-button" onClick={logout} disabled={signingOut}>Salir de esta cuenta</button></main>;
  const history = location.pathname.startsWith('/historial');
  return <div className="app-shell"><aside className="sidebar"><Brand /><span className="sidebar-label">TU ESPACIO</span><nav aria-label="Navegación principal"><Link to="/" className={!history ? 'nav-item active' : 'nav-item'}><BookOpen size={19} />Mis cursos<ChevronRight size={15} /></Link><Link to="/historial" className={history ? 'nav-item active' : 'nav-item'}><CalendarDays size={19} />Historial</Link></nav><div className="sidebar-note"><span className="small-mark"><QrCode size={24} /></span><strong>Una clase.<br />Un QR. Todos presentes.</strong><p>Vos enseñás.<br />El resto, lo hacemos simple.</p></div><div className="account"><span className="avatar">{profile.name.slice(0, 1).toUpperCase()}</span><div><strong>{profile.name}</strong><span>Profesor</span></div><button className="icon-button" onClick={logout} disabled={signingOut} aria-label="Cerrar sesión"><LogOut size={17} /></button></div></aside><div className="workspace"><header className="topbar"><span>ASISTENCIA UNIVERSITARIA</span><span className="today"><span className="status-dot" />{date(new Date().toISOString())}</span></header>{error && <ErrorNotice text={error} />}<Outlet context={profile} /></div></div>;
}
export function Dashboard({ history = false }: { history?: boolean }) {
  const profile = useOutletContext<Profile>();
  const [courses, setCourses] = useState<Course[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState('');
  const [create, setCreate] = useState(false); const [courseModal, setCourseModal] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setCourses(await allPages<Course>(`/courses?includeArchived=${history}`)); } catch (e) { setError(message(e)); } finally { setLoading(false); } }, [history]);
  useEffect(() => { void load(); }, [load]);
  const filtered = courses.filter(c => c.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return <main className="page"><div className="page-heading"><div><span className="eyebrow">{history ? 'CADA CLASE CUENTA' : `HOLA, ${profile.name.split(' ')[0].toUpperCase()}`}</span><h1>{history ? 'Tu historial.' : 'Mis cursos.'}</h1><p>{history ? 'Volvé a tus clases y consultá quién estuvo presente.' : 'Todo listo para tu próxima clase.'}</p></div><button className="button primary" onClick={() => setCreate(true)}><Plus size={19} />Tomar asistencia</button></div>
    {!history && <section className="welcome-banner"><div className="banner-icon"><QrCode size={32} /></div><div><h2>Pasar lista ya es cosa del pasado.</h2><p>Elegí un curso, generá el QR y empezá tu clase.</p></div><span className="banner-label">ESCANEAR <ArrowRight size={13} /> PRESENTE <CheckMark /></span></section>}
    <div className="section-heading"><h2>{history ? 'Todos tus cursos' : 'Tus cursos'} <span className="count-pill">{courses.length}</span></h2><div className="section-controls"><label className="search-field"><Search size={17} /><input aria-label="Buscar curso" placeholder="Buscar curso…" value={search} onChange={e => setSearch(e.target.value)} /></label>{!history && <button className="text-button" onClick={() => setCourseModal(true)}><Plus size={16} />Nuevo curso</button>}</div></div>
    {error && <ErrorNotice text={error} retry={load} />}{loading ? <Loading text="Cargando cursos…" /> : <div className="course-grid">{filtered.map((course, index) => <Link className={`course-card color-${index % 3}`} key={course.id} to={`/cursos/${course.id}`}><div className="course-card-top"><span className="course-icon"><BookOpen size={23} /></span><ArrowRight size={20} /></div><span className="eyebrow">{course.archived_at ? 'ARCHIVADO' : 'CURSO'}</span><h3>{course.name}</h3><div className="course-card-footer"><span>{course.class_count} {course.class_count === 1 ? 'clase' : 'clases'}</span><span>Ver clases <ChevronRight size={14} /></span></div></Link>)}{!history && !search && <button className="new-course-card" onClick={() => setCourseModal(true)}><span><Plus size={24} /></span><strong>Un nuevo comienzo</strong><p>Creá tu próximo curso</p></button>}</div>}
    {!loading && filtered.length === 0 && (search || history) && <div className="empty-state"><Search size={30} /><h3>{search ? 'No encontramos ese curso' : 'Tu historia empieza en la próxima clase'}</h3><p>{search ? 'Probá con otro nombre.' : 'Las clases que crees aparecerán acá.'}</p></div>}
    <footer className="page-footer"><span className="status-dot" />Presente. Para estar donde importa.</footer>
    {create && <CreateSession courses={courses.filter(c => !c.archived_at)} onClose={() => setCreate(false)} />}
    {courseModal && <CreateCourse onClose={() => setCourseModal(false)} onCreated={() => { setCourseModal(false); void load(); }} />}
  </main>;
}
function CheckMark() { return <span className="tiny-check">✓</span>; }
function CreateCourse({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); if (busy) return; setBusy(true); setError(''); try { await api('/courses', { body: { name: name.trim() } }); onCreated(); } catch (e) { setError(`${message(e)} Revisá la lista antes de crear el curso otra vez.`); setBusy(false); } }
  return <Modal title="Nuevo curso" onClose={() => { if (!busy) onClose(); }}><form onSubmit={submit}><p className="form-intro">Solo necesitamos un nombre para empezar.</p><label>Nombre del curso<input autoFocus required maxLength={120} value={name} onChange={e => setName(e.target.value)} placeholder="Ej. Coaching N1" /></label>{error && <ErrorNotice text={error} />}<button className="button primary full" disabled={busy || !name.trim()}>{busy ? 'Creando…' : 'Crear curso'}</button></form></Modal>;
}
export function CreateSession({ courses, selected, onClose }: { courses: Course[]; selected?: string; onClose: () => void }) {
  const navigate = useNavigate(); const [courseId, setCourseId] = useState(selected || courses[0]?.id || 'new'); const [courseName, setCourseName] = useState('');
  const [name, setName] = useState(`Clase ${(courses.find(c => c.id === (selected || courses[0]?.id))?.class_count || 0) + 1}`); const [duration, setDuration] = useState(5); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) {
    event.preventDefault(); if (busy) return; setBusy(true); setError('');
    try { const session = await api<{ id: string }>('/attendance-sessions', { body: { ...(courseId === 'new' ? { courseName: courseName.trim() } : { courseId }), name: name.trim(), durationMinutes: duration } }); navigate(`/sesiones/${session.id}`); }
    catch (e) { setError(`${message(e)} Si hubo un problema de conexión, revisá las clases antes de volver a generar.`); setBusy(false); }
  }
  return <Modal title="Tomar asistencia" onClose={() => { if (!busy) onClose(); }}><form onSubmit={submit}><p className="form-intro">Prepará la clase. Nosotros nos ocupamos del resto.</p><label>Curso<select value={courseId} onChange={e => { setCourseId(e.target.value); setName(`Clase ${(courses.find(c => c.id === e.target.value)?.class_count || 0) + 1}`); }}>{courses.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}<option value="new">+ Crear nuevo curso</option></select></label>{courseId === 'new' && <label>Nombre del nuevo curso<input required maxLength={120} placeholder="Ej. Coaching N1" value={courseName} onChange={e => setCourseName(e.target.value)} /></label>}<label>Nombre de la clase<input required maxLength={120} value={name} onChange={e => setName(e.target.value)} /></label><fieldset><legend>¿Cuánto tiempo dejamos abierta la asistencia?</legend><div className="duration-options">{[2, 5, 10].map(n => <label className={duration === n ? 'selected' : ''} key={n}><input type="radio" name="duration" value={n} checked={duration === n} onChange={() => setDuration(n)} />{n} minutos{n === 5 && <span>Recomendado</span>}</label>)}</div></fieldset>{error && <ErrorNotice text={error} />}<button className="button primary full" disabled={busy || !name.trim() || (courseId === 'new' && !courseName.trim())}><QrCode size={18} />{busy ? 'Preparando la clase…' : 'Generar QR'}</button><p className="form-footnote">La asistencia empieza al generar el código.</p></form></Modal>;
}
export function CoursePage() {
  const { id } = useParams(); const [course, setCourse] = useState<Course | null>(null); const [classes, setClasses] = useState<ClassItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [create, setCreate] = useState(false); const [archive, setArchive] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [courses, rows] = await Promise.all([allPages<Course>('/courses?includeArchived=true'), allPages<ClassItem>(`/courses/${id}/classes`)]); setCourse(courses.find(c => c.id === id) || null); setClasses(rows); } catch (e) { setError(message(e)); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  return <main className="page"><Link to="/" className="back-link"><ArrowLeft size={16} />Mis cursos</Link>{error && <ErrorNotice text={error} retry={load} />}{loading ? <Loading /> : course ? <><div className="page-heading"><div><span className="eyebrow">{course.archived_at ? 'CURSO ARCHIVADO' : 'TU CURSO'}</span><h1>{course.name}</h1><p>Un registro de cada encuentro.</p></div>{!course.archived_at && <button className="button primary" onClick={() => setCreate(true)}><Plus size={18} />Tomar asistencia</button>}</div><div className="section-heading"><h2>Clases <span className="count-pill">{classes.length}</span></h2>{!course.archived_at && <button className="text-button muted" onClick={() => setArchive(true)}><Archive size={16} />Archivar curso</button>}</div><div className="class-list">{classes.map(c => <Link to={`/sesiones/${c.session_id}`} className="class-row" key={c.id}><span className="class-date-icon"><CalendarDays size={23} /></span><div><h3>{c.name}</h3><span>{date(c.class_date)}</span></div><span className={`pill ${c.session_status === 'OPEN' ? 'green' : ''}`}>{c.archived_at ? 'Archivada' : c.session_status === 'OPEN' ? 'Abierta' : 'Finalizada'}</span><span className="class-count"><strong>{c.present_count}</strong> presentes</span><ArrowRight size={18} /></Link>)}</div>{classes.length === 0 && <div className="empty-state"><BookOpen size={34} /><h3>Tu primera clase te espera</h3><p>Tomá asistencia para empezar el historial de este curso.</p></div>}{create && <CreateSession courses={[course]} selected={course.id} onClose={() => setCreate(false)} />}{archive && <ArchiveModal path={`/courses/${course.id}/archive`} noun="curso" onClose={() => setArchive(false)} onDone={() => { setArchive(false); void load(); }} />}</> : !error && <p>No encontramos el curso.</p>}</main>;
}
export function ArchiveModal({ path, noun, onClose, onDone }: { path: string; noun: string; onClose: () => void; onDone: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [requiresConfirmation, setRequiresConfirmation] = useState(false);
  async function submit() {
    setBusy(true); setError('');
    try { await api(path, { body: { confirmWithAttendance: requiresConfirmation } }); onDone(); }
    catch (e) { if (e instanceof ApiError && e.code === 'ARCHIVE_CONFIRMATION_REQUIRED') setRequiresConfirmation(true); else setError(message(e)); setBusy(false); }
  }
  return <Modal title={`Archivar ${noun}`} onClose={() => { if (!busy) onClose(); }}><p className="form-intro">{requiresConfirmation ? `Este ${noun} tiene asistencias registradas. ¿Confirmás que querés archivarlo?` : `El ${noun} dejará de estar activo. El historial se conserva y los intentos de asistencia pendientes se cancelan.`}</p>{error && <ErrorNotice text={error} />}<div className="modal-actions"><button className="button secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className="button danger" onClick={submit} disabled={busy}>{busy ? 'Archivando…' : requiresConfirmation ? 'Sí, archivar con asistencias' : 'Archivar'}</button></div></Modal>;
}
